import { rm, writeFile } from "node:fs/promises";

async function safeRm(path) {
  try {
    await rm(path, { force: true });
  } catch {
    // ignore
  }
}

// Cloudflare Pages sometimes redirects to dist/client/wrangler.json (generated by tooling).
// Ensure that file is safe/minimal (no triggers, no beta fields) to avoid Wrangler validation failures.
const minimalWrangler = {
  name: "sintype",
  pages_build_output_dir: "./dist/client",
  compatibility_date: "2024-05-28",
  compatibility_flags: ["nodejs_compat"],
};

try {
  await writeFile(
    "dist/client/wrangler.json",
    JSON.stringify(minimalWrangler, null, 2) + "\n",
    "utf8",
  );
} catch {
  // ignore
}

await safeRm("dist/client/wrangler.jsonc");
await safeRm("dist/wrangler.json");
await safeRm("dist/wrangler.jsonc");

