/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteMapRouteImport } from './routes/site-map'
import { Route as SinhalaUnicodeConverterRouteImport } from './routes/sinhala-unicode-converter'
import { Route as SinglishToSinhalaRouteImport } from './routes/singlish-to-sinhala'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MSessionIdRouteImport } from './routes/m.$sessionId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard.index'
import { Route as MLocalSessionIdRouteImport } from './routes/m.local.$sessionId'
import { Route as ApiSinhalaLearnRouteImport } from './routes/api/sinhala/learn'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminContentRouteImport } from './routes/api/admin/content'
import { Route as ApiAdminBlogRouteImport } from './routes/api/admin/blog'
import { Route as AdminDashboardUsersRouteImport } from './routes/admin/dashboard.users'
import { Route as AdminDashboardUpdatesRouteImport } from './routes/admin/dashboard.updates'
import { Route as AdminDashboardNotificationsRouteImport } from './routes/admin/dashboard.notifications'
import { Route as AdminDashboardLicenseResetsRouteImport } from './routes/admin/dashboard.license-resets'
import { Route as AdminDashboardFeedbackRouteImport } from './routes/admin/dashboard.feedback'
import { Route as AdminDashboardContentRouteImport } from './routes/admin/dashboard.content'
import { Route as AdminDashboardBlogRouteImport } from './routes/admin/dashboard.blog'
import { Route as ApiAdminBlogIdRouteImport } from './routes/api/admin/blog.$id'
import { Route as AdminDashboardContentNewRouteImport } from './routes/admin/dashboard.content.new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMapRoute = SiteMapRouteImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SinhalaUnicodeConverterRoute = SinhalaUnicodeConverterRouteImport.update({
  id: '/sinhala-unicode-converter',
  path: '/sinhala-unicode-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglishToSinhalaRoute = SinglishToSinhalaRouteImport.update({
  id: '/singlish-to-sinhala',
  path: '/singlish-to-sinhala',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MSessionIdRoute = MSessionIdRouteImport.update({
  id: '/m/$sessionId',
  path: '/m/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const MLocalSessionIdRoute = MLocalSessionIdRouteImport.update({
  id: '/m/local/$sessionId',
  path: '/m/local/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSinhalaLearnRoute = ApiSinhalaLearnRouteImport.update({
  id: '/api/sinhala/learn',
  path: '/api/sinhala/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogRoute = ApiAdminBlogRouteImport.update({
  id: '/api/admin/blog',
  path: '/api/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardUpdatesRoute = AdminDashboardUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardNotificationsRoute =
  AdminDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardLicenseResetsRoute =
  AdminDashboardLicenseResetsRouteImport.update({
    id: '/license-resets',
    path: '/license-resets',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardFeedbackRoute = AdminDashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardContentRoute = AdminDashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardBlogRoute = AdminDashboardBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const ApiAdminBlogIdRoute = ApiAdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBlogRoute,
} as any)
const AdminDashboardContentNewRoute =
  AdminDashboardContentNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminDashboardContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/singlish-to-sinhala': typeof SinglishToSinhalaRoute
  '/sinhala-unicode-converter': typeof SinhalaUnicodeConverterRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/dashboard/blog': typeof AdminDashboardBlogRoute
  '/admin/dashboard/content': typeof AdminDashboardContentRouteWithChildren
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/license-resets': typeof AdminDashboardLicenseResetsRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/admin/blog': typeof ApiAdminBlogRouteWithChildren
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/m/local/$sessionId': typeof MLocalSessionIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/content/new': typeof AdminDashboardContentNewRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/singlish-to-sinhala': typeof SinglishToSinhalaRoute
  '/sinhala-unicode-converter': typeof SinhalaUnicodeConverterRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/dashboard/blog': typeof AdminDashboardBlogRoute
  '/admin/dashboard/content': typeof AdminDashboardContentRouteWithChildren
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/license-resets': typeof AdminDashboardLicenseResetsRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/admin/blog': typeof ApiAdminBlogRouteWithChildren
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/m/local/$sessionId': typeof MLocalSessionIdRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/dashboard/content/new': typeof AdminDashboardContentNewRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/singlish-to-sinhala': typeof SinglishToSinhalaRoute
  '/sinhala-unicode-converter': typeof SinhalaUnicodeConverterRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/dashboard/blog': typeof AdminDashboardBlogRoute
  '/admin/dashboard/content': typeof AdminDashboardContentRouteWithChildren
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/license-resets': typeof AdminDashboardLicenseResetsRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/admin/blog': typeof ApiAdminBlogRouteWithChildren
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/m/local/$sessionId': typeof MLocalSessionIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/content/new': typeof AdminDashboardContentNewRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/contact'
    | '/download'
    | '/faq'
    | '/feedback'
    | '/license'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/singlish-to-sinhala'
    | '/sinhala-unicode-converter'
    | '/site-map'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/m/$sessionId'
    | '/admin/'
    | '/blog/'
    | '/admin/dashboard/blog'
    | '/admin/dashboard/content'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/license-resets'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/admin/blog'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/sinhala/learn'
    | '/m/local/$sessionId'
    | '/admin/dashboard/'
    | '/admin/dashboard/content/new'
    | '/api/admin/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/download'
    | '/faq'
    | '/feedback'
    | '/license'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/singlish-to-sinhala'
    | '/sinhala-unicode-converter'
    | '/site-map'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/m/$sessionId'
    | '/admin'
    | '/blog'
    | '/admin/dashboard/blog'
    | '/admin/dashboard/content'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/license-resets'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/admin/blog'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/sinhala/learn'
    | '/m/local/$sessionId'
    | '/admin/dashboard'
    | '/admin/dashboard/content/new'
    | '/api/admin/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/contact'
    | '/download'
    | '/faq'
    | '/feedback'
    | '/license'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/singlish-to-sinhala'
    | '/sinhala-unicode-converter'
    | '/site-map'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/m/$sessionId'
    | '/admin/'
    | '/blog/'
    | '/admin/dashboard/blog'
    | '/admin/dashboard/content'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/license-resets'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/admin/blog'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/sinhala/learn'
    | '/m/local/$sessionId'
    | '/admin/dashboard/'
    | '/admin/dashboard/content/new'
    | '/api/admin/blog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  SinglishToSinhalaRoute: typeof SinglishToSinhalaRoute
  SinhalaUnicodeConverterRoute: typeof SinhalaUnicodeConverterRoute
  SiteMapRoute: typeof SiteMapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MSessionIdRoute: typeof MSessionIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAdminBlogRoute: typeof ApiAdminBlogRouteWithChildren
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiSinhalaLearnRoute: typeof ApiSinhalaLearnRoute
  MLocalSessionIdRoute: typeof MLocalSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinhala-unicode-converter': {
      id: '/sinhala-unicode-converter'
      path: '/sinhala-unicode-converter'
      fullPath: '/sinhala-unicode-converter'
      preLoaderRoute: typeof SinhalaUnicodeConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singlish-to-sinhala': {
      id: '/singlish-to-sinhala'
      path: '/singlish-to-sinhala'
      fullPath: '/singlish-to-sinhala'
      preLoaderRoute: typeof SinglishToSinhalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/m/$sessionId': {
      id: '/m/$sessionId'
      path: '/m/$sessionId'
      fullPath: '/m/$sessionId'
      preLoaderRoute: typeof MSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/m/local/$sessionId': {
      id: '/m/local/$sessionId'
      path: '/m/local/$sessionId'
      fullPath: '/m/local/$sessionId'
      preLoaderRoute: typeof MLocalSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sinhala/learn': {
      id: '/api/sinhala/learn'
      path: '/api/sinhala/learn'
      fullPath: '/api/sinhala/learn'
      preLoaderRoute: typeof ApiSinhalaLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blog': {
      id: '/api/admin/blog'
      path: '/api/admin/blog'
      fullPath: '/api/admin/blog'
      preLoaderRoute: typeof ApiAdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/users': {
      id: '/admin/dashboard/users'
      path: '/users'
      fullPath: '/admin/dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/updates': {
      id: '/admin/dashboard/updates'
      path: '/updates'
      fullPath: '/admin/dashboard/updates'
      preLoaderRoute: typeof AdminDashboardUpdatesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/notifications': {
      id: '/admin/dashboard/notifications'
      path: '/notifications'
      fullPath: '/admin/dashboard/notifications'
      preLoaderRoute: typeof AdminDashboardNotificationsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/license-resets': {
      id: '/admin/dashboard/license-resets'
      path: '/license-resets'
      fullPath: '/admin/dashboard/license-resets'
      preLoaderRoute: typeof AdminDashboardLicenseResetsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/feedback': {
      id: '/admin/dashboard/feedback'
      path: '/feedback'
      fullPath: '/admin/dashboard/feedback'
      preLoaderRoute: typeof AdminDashboardFeedbackRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/content': {
      id: '/admin/dashboard/content'
      path: '/content'
      fullPath: '/admin/dashboard/content'
      preLoaderRoute: typeof AdminDashboardContentRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/blog': {
      id: '/admin/dashboard/blog'
      path: '/blog'
      fullPath: '/admin/dashboard/blog'
      preLoaderRoute: typeof AdminDashboardBlogRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/api/admin/blog/$id': {
      id: '/api/admin/blog/$id'
      path: '/$id'
      fullPath: '/api/admin/blog/$id'
      preLoaderRoute: typeof ApiAdminBlogIdRouteImport
      parentRoute: typeof ApiAdminBlogRoute
    }
    '/admin/dashboard/content/new': {
      id: '/admin/dashboard/content/new'
      path: '/new'
      fullPath: '/admin/dashboard/content/new'
      preLoaderRoute: typeof AdminDashboardContentNewRouteImport
      parentRoute: typeof AdminDashboardContentRoute
    }
  }
}

interface AdminDashboardContentRouteChildren {
  AdminDashboardContentNewRoute: typeof AdminDashboardContentNewRoute
}

const AdminDashboardContentRouteChildren: AdminDashboardContentRouteChildren = {
  AdminDashboardContentNewRoute: AdminDashboardContentNewRoute,
}

const AdminDashboardContentRouteWithChildren =
  AdminDashboardContentRoute._addFileChildren(
    AdminDashboardContentRouteChildren,
  )

interface AdminDashboardRouteChildren {
  AdminDashboardBlogRoute: typeof AdminDashboardBlogRoute
  AdminDashboardContentRoute: typeof AdminDashboardContentRouteWithChildren
  AdminDashboardFeedbackRoute: typeof AdminDashboardFeedbackRoute
  AdminDashboardLicenseResetsRoute: typeof AdminDashboardLicenseResetsRoute
  AdminDashboardNotificationsRoute: typeof AdminDashboardNotificationsRoute
  AdminDashboardUpdatesRoute: typeof AdminDashboardUpdatesRoute
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardBlogRoute: AdminDashboardBlogRoute,
  AdminDashboardContentRoute: AdminDashboardContentRouteWithChildren,
  AdminDashboardFeedbackRoute: AdminDashboardFeedbackRoute,
  AdminDashboardLicenseResetsRoute: AdminDashboardLicenseResetsRoute,
  AdminDashboardNotificationsRoute: AdminDashboardNotificationsRoute,
  AdminDashboardUpdatesRoute: AdminDashboardUpdatesRoute,
  AdminDashboardUsersRoute: AdminDashboardUsersRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminBlogRouteChildren {
  ApiAdminBlogIdRoute: typeof ApiAdminBlogIdRoute
}

const ApiAdminBlogRouteChildren: ApiAdminBlogRouteChildren = {
  ApiAdminBlogIdRoute: ApiAdminBlogIdRoute,
}

const ApiAdminBlogRouteWithChildren = ApiAdminBlogRoute._addFileChildren(
  ApiAdminBlogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  SinglishToSinhalaRoute: SinglishToSinhalaRoute,
  SinhalaUnicodeConverterRoute: SinhalaUnicodeConverterRoute,
  SiteMapRoute: SiteMapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  MSessionIdRoute: MSessionIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAdminBlogRoute: ApiAdminBlogRouteWithChildren,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiSinhalaLearnRoute: ApiSinhalaLearnRoute,
  MLocalSessionIdRoute: MLocalSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
