/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MSessionIdRouteImport } from './routes/m.$sessionId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard.index'
import { Route as ApiSinhalaLearnRouteImport } from './routes/api/sinhala/learn'
import { Route as AdminDashboardUsersRouteImport } from './routes/admin/dashboard.users'
import { Route as AdminDashboardUpdatesRouteImport } from './routes/admin/dashboard.updates'
import { Route as AdminDashboardNotificationsRouteImport } from './routes/admin/dashboard.notifications'
import { Route as AdminDashboardFeedbackRouteImport } from './routes/admin/dashboard.feedback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MSessionIdRoute = MSessionIdRouteImport.update({
  id: '/m/$sessionId',
  path: '/m/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const ApiSinhalaLearnRoute = ApiSinhalaLearnRouteImport.update({
  id: '/api/sinhala/learn',
  path: '/api/sinhala/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardUpdatesRoute = AdminDashboardUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardNotificationsRoute =
  AdminDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardFeedbackRoute = AdminDashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/m/$sessionId': typeof MSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/feedback': typeof AdminDashboardFeedbackRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/updates': typeof AdminDashboardUpdatesRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/sinhala/learn': typeof ApiSinhalaLearnRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/download'
    | '/faq'
    | '/license'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/m/$sessionId'
    | '/admin/'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/sinhala/learn'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/faq'
    | '/license'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/m/$sessionId'
    | '/admin'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/sinhala/learn'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/download'
    | '/faq'
    | '/license'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/m/$sessionId'
    | '/admin/'
    | '/admin/dashboard/feedback'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/updates'
    | '/admin/dashboard/users'
    | '/api/sinhala/learn'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  MSessionIdRoute: typeof MSessionIdRoute
  ApiSinhalaLearnRoute: typeof ApiSinhalaLearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/m/$sessionId': {
      id: '/m/$sessionId'
      path: '/m/$sessionId'
      fullPath: '/m/$sessionId'
      preLoaderRoute: typeof MSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/api/sinhala/learn': {
      id: '/api/sinhala/learn'
      path: '/api/sinhala/learn'
      fullPath: '/api/sinhala/learn'
      preLoaderRoute: typeof ApiSinhalaLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/users': {
      id: '/admin/dashboard/users'
      path: '/users'
      fullPath: '/admin/dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/updates': {
      id: '/admin/dashboard/updates'
      path: '/updates'
      fullPath: '/admin/dashboard/updates'
      preLoaderRoute: typeof AdminDashboardUpdatesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/notifications': {
      id: '/admin/dashboard/notifications'
      path: '/notifications'
      fullPath: '/admin/dashboard/notifications'
      preLoaderRoute: typeof AdminDashboardNotificationsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/feedback': {
      id: '/admin/dashboard/feedback'
      path: '/feedback'
      fullPath: '/admin/dashboard/feedback'
      preLoaderRoute: typeof AdminDashboardFeedbackRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardFeedbackRoute: typeof AdminDashboardFeedbackRoute
  AdminDashboardNotificationsRoute: typeof AdminDashboardNotificationsRoute
  AdminDashboardUpdatesRoute: typeof AdminDashboardUpdatesRoute
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardFeedbackRoute: AdminDashboardFeedbackRoute,
  AdminDashboardNotificationsRoute: AdminDashboardNotificationsRoute,
  AdminDashboardUpdatesRoute: AdminDashboardUpdatesRoute,
  AdminDashboardUsersRoute: AdminDashboardUsersRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  MSessionIdRoute: MSessionIdRoute,
  ApiSinhalaLearnRoute: ApiSinhalaLearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
