// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseEnv() {
  // Strictly use Vite env vars (works locally via `.env` and in production via Netlify env vars)
  const url = (import.meta as any).env?.VITE_SUPABASE_URL;
  const anon = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY;
  return {
    url: typeof url === 'string' ? url : '',
    anon: typeof anon === 'string' ? anon : '',
  };
}

export const SUPABASE_CONFIGURED = (() => {
  const { url, anon } = getSupabaseEnv();
  return Boolean(url && anon);
})();

function createSupabaseClient() {
  const { url: SUPABASE_URL, anon: SUPABASE_ANON_KEY } = getSupabaseEnv();

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_ANON_KEY ? ['VITE_SUPABASE_ANON_KEY'] : []),
    ];
    const message =
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      `Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable auth/sync/telemetry.`;
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      storageKey: 'sintype-auth-token',
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

