// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseEnv() {
  const url =
    (import.meta as any).env?.VITE_SUPABASE_URL || (process as any).env?.SUPABASE_URL;
  const anon =
    (import.meta as any).env?.VITE_SUPABASE_ANON_KEY ||
    (process as any).env?.SUPABASE_ANON_KEY;
  return {
    url: typeof url === 'string' ? url : '',
    anon: typeof anon === 'string' ? anon : '',
  };
}

export const SUPABASE_CONFIGURED = (() => {
  const { url, anon } = getSupabaseEnv();
  return Boolean(url && anon);
})();

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const { url: SUPABASE_URL, anon: SUPABASE_ANON_KEY } = getSupabaseEnv();

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_ANON_KEY ? ['SUPABASE_ANON_KEY'] : []),
    ];
    const message =
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      `Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable auth/sync/telemetry.`;
    // Don't throw here; allow the app to run without Supabase (converter still works).
    console.warn(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

